#! /bin/bash
echo "Making a request to a pokemon pikachu API"

URL='https://pokeapi.co/api/v2/pokemon/'
OUTPUT_FILE='data.json'
STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
RESPONSE=$(curl $URL)
ERROR_FILE='errors.txt'

if [[ "$STATUS_CODE" -eq 200 ]]; then
    echo "$RESPONSE" | jq . > "$OUTPUT_FILE"
    echo "Saved to file"
else
    echo $(date) - FAILED TO LOAD INTO FILE > "$ERROR_FILE"
    echo  "Error retrieving api"
fi
