#!/bin/bash

FILE_PATH='data.json'

# make dir to store pikomon files

mkdir -p pokemons

# Pikomon names
POKEMONS_NAMES=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon" "charizard")

for pokemon in "${POKEMONS_NAMES[@]}"; do
    echo Processing request for "$pokemon"......
    pokemon_url=$(jq -r --arg n "$pokemon" '.results[] | select(.name==$n) | .url' data.json)
    status_code=$(curl -s -o /dev/null -w "%{http_code}" $pokemon_url)

    for i in {1..3}; do
        if [[ "$status_code" -eq 200 ]]; then
            file_path=pokemons/$pokemon.json
            response=$(curl "$pokemon_url")
            echo Saving data in "$file_path"
            echo "$response" | jq . > "$file_path"

            echo  Data saved
        else
            echo Error occured. retrying .....
        fi
        # wait for two seconds to avoid rate limiting issues
        sleep 2
    done

    echo Unknown Error occured while retrieving $pokemon!
done