#!/bin/bash

FILE_NAME='data.json'

echo Extracting the Pokémon’s name, height, weight, and type from the $FILE_NAME file

name=$(jq -r ".forms[0].name" $FILE_NAME | sed 's/.*/\u&/')
height=$(jq -r ".height" $FILE_NAME)
weight=$(jq -r ".weight" $FILE_NAME)
type=$(jq -r ".type" $FILE_NAME)

# converts weights to kg  and height to meters
formatted_weight=$(echo "$height" | awk '{ print $1/10}')
formatted_height=$(echo "$weight" | awk '{print $1/10}')

echo $name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.