#!/bin/bash

FILE_NAME='data.json'

echo Extracting the Pokémon’s name, height, weight, and type from the $FILE_NAME file

name=$(jq -r ".forms[0].name" $FILE_NAME | sed 's/.*/\u&/')
height=$(jq -r ".height" $FILE_NAME)
weight=$(jq -r ".weight" $FILE_NAME)
type=$(jq -r ".type" $FILE_NAME)

# converts weights and height
height_m=$(echo "$height" | awk '{ print $1/10}')
weight_kg=$(echo "$weight" | awk '{print $1/10}')

echo "$name" is of "$type" Electric, weighs "$weight_kg", and is "$height_m" tall.